# Title: Codacy Coverage Reporter
# Author: Codacy
# Date: 2021
# Availability: https://github.com/codacy/codacy-coverage-reporter-action

name: codacy-coverage-reporter

on:
  pull_request:
    branches: main

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: lcov.info